### ISSUE TITLE
求添加一下我们的文章Rethinking Performance Estimation in Neural Architecture Search

### ISSUE THREAD

**Issue by zhengxiawu** [amusi/CVPR2020-Code#1]
目前已中
论文标题：Rethinking Performance Estimation in Neural Architecture Search
论文：准备中
代码：https://github.com/zhengxiawu/rethinking_performance_estimation_in_NAS
解读：https://www.zhihu.com/question/372070853/answer/1035234510

如能添加，非常感谢！

**Comment by amusi** [comment]
> 目前已中
> 论文标题：Rethinking Performance Estimation in Neural Architecture Search
> 论文：准备中
> 代码：https://github.com/zhengxiawu/rethinking_performance_estimation_in_NAS
> 解读：https://www.zhihu.com/question/372070853/answer/1035234510
> 
> 如能添加，非常感谢！

ok，已添加，感谢大佬分享
