### ISSUE TITLE
[CVPR2020] Learning Meta Face Recognition in Unseen Domains

### ISSUE THREAD

**Issue by cleardusk** [amusi/CVPR2020-Code#10]
方向：跨域人脸识别
论文标题：Learning Meta Face Recognition in Unseen Domains
论文：[ArXiv](https://arxiv.org/pdf/2003.07733.pdf) or [here](https://me.guojianzhu.com/assets/pdfs/05997.pdf)
协议 & 评测代码：https://github.com/cleardusk/MFR （更新中）
软文：https://mp.weixin.qq.com/s/YZoEnjpnlvb90qSI3xdJqQ

如能添加，非常感谢！

**Comment by amusi** [comment]
感谢分享，现已添加
