### ISSUE TITLE
[CVPR2020] EfficientDet: Scalable and Efficient Object Detection

### ISSUE THREAD

**Issue by duanzhiihao** [amusi/CVPR2020-Code#11]
方向：目标检测
题目：EfficientDet: Scalable and Efficient Object Detection
ArXiv: [https://arxiv.org/abs/1911.09070](https://arxiv.org/abs/1911.09070)
GitHub: [https://github.com/google/automl/tree/master/efficientdet](https://github.com/google/automl/tree/master/efficientdet)

无意间发现的很不错的文章，好像这里漏掉了

**Comment by amusi** [comment]
好的，现已添加，感谢分享
