### ISSUE TITLE
CVPR2020 Polarized Reflection Removal

### ISSUE THREAD

**Issue by ChenyangLEI** [amusi/CVPR2020-Code#12]
用偏振相机做去反光，后续会开源代码以及数据集。

project website: https://leichenyang.weebly.com/project-polarized.html
code: https://github.com/ChenyangLEI/CVPR2020-Polarized-Reflection-Removal-with-Perfect-Alignment

非常感谢！

**Comment by amusi** [comment]
感谢分享，现已添加
