### ISSUE TITLE
目标跟踪方面论文两篇

### ISSUE THREAD

**Issue by wangdongdut** [amusi/CVPR2020-Code#13]
Kenan Dai, Yunhua Zhang, Dong Wang, Jianhua Li, Huchuan Lu, Xiaoyun Yang, High-Performance Long-Term Tracking with Meta-Updater, CVPR2020
论文：https://arxiv.org/abs/2004.00305
代码：https://github.com/Daikenan/LTMU

Bin Yan, Dong Wang, Huchuan Lu, Xiaoyun Yang, Cooling-Shrinking Attack: Blinding the Tracker with Imperceptible Noises, CVPR2020
论文：https://arxiv.org/abs/2003.09595
代码：https://github.com/MasterBin-IIAU/CSA

**Comment by amusi** [comment]
感谢分享，现已添加
