### ISSUE TITLE
新增模型压缩相关文章一篇，感谢

### ISSUE THREAD

**Issue by htqin** [amusi/CVPR2020-Code#17]
模型压缩（二值神经网络）相关文章一篇，已中
论文标题：Forward and Backward Information Retention for Accurate Binary Neural Networks
论文arXiv链接：https://arxiv.org/abs/1909.10788
代码：https://github.com/htqin/IR-Net/

**Comment by amusi** [comment]
感谢分享，现已添加

**Comment by htqin** [comment]
该篇文章属于神经网络模型压缩，不是视频压缩（目前分类），希望修正一下

**Comment by amusi** [comment]
感谢提醒，现已修正
