### ISSUE TITLE
图像分类 

### ISSUE THREAD

**Issue by ReverseSystem001** [amusi/CVPR2020-Code#18]
代码： https://github.com/ildoonet/spatially-attentive-output-layer this link reports 404. do you have the code? hope your replay

**Comment by amusi** [comment]
据我了解，这篇论文的代码好像被原作者删除了（代码库没有了），但我新增了论文链接，你可以看一下。估计我过段时间会被这篇论文从这个项目中撤掉，因为确实代码链接无效了

**Comment by ReverseSystem001** [comment]
嗯嗯，好吧！这个git贼六，多谢多谢。------------------ 原始邮件 ------------------
发件人: "Amusi"<notifications@github.com>
发送时间: 2020年4月28日(星期二) 凌晨0:07
收件人: "amusi/CVPR2020-Code"<CVPR2020-Code@noreply.github.com>;
抄送: "reverseSystem"<892379162@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [amusi/CVPR2020-Code] 图像分类  (#18)




 
据我了解，这篇论文的代码好像被原作者删除了（代码库没有了），但我新增了论文链接，你可以看一下。估计我过段时间会被这篇论文从这个项目中撤掉，因为确实代码链接无效了
 
&mdash;
