### ISSUE TITLE
融合惯导和多视角图像的3D人体姿态估计

### ISSUE THREAD

**Issue by zhezh** [amusi/CVPR2020-Code#20]
Fusing Wearable IMUs with Multi-View Images for Human Pose Estimation: A Geometric Approach (CVPR 2020)

project page: https://www.zhe-zhang.com/cvpr2020
code framework：pytorch
SOTA experimental results on TotalCapture Dataset

**Comment by amusi** [comment]
> Fusing Wearable IMUs with Multi-View Images for Human Pose Estimation: A Geometric Approach (CVPR 2020)
> 
> project page: https://www.zhe-zhang.com/cvpr2020
> code framework：pytorch
> SOTA experimental results on TotalCapture Dataset

感谢分享，现已添加
