### ISSUE TITLE
[语义场景补全] 论文1篇

### ISSUE THREAD

**Issue by charlesCXK** [amusi/CVPR2020-Code#21]
3D Sketch-aware Semantic Scene Completion via Semi-supervised Structure Prior

论文：[https://arxiv.org/abs/2003.14052](https://arxiv.org/abs/2003.14052)
代码：[https://github.com/charlesCXK/3D-SketchAware-SSC](https://github.com/charlesCXK/3D-SketchAware-SSC)

Thank you very much !

**Comment by amusi** [comment]
> 3D Sketch-aware Semantic Scene Completion via Semi-supervised Structure Prior
> 
> 论文：https://arxiv.org/abs/2003.14052
> 代码：https://github.com/charlesCXK/3D-SketchAware-SSC
> 
> Thank you very much !

感谢分享，现已添加
