### ISSUE TITLE
添加一篇GAN相关的CVPR 2020 Oral Paper

### ISSUE THREAD

**Issue by wtjiang98** [amusi/CVPR2020-Code#23]
PSGAN: Pose and Expression Robust Spatial-Aware GAN for Customizable Makeup Transfer
(CVPR 2020 **Oral**)

paper: https://arxiv.org/abs/1909.06956
code: https://github.com/wtjiang98/PSGAN

**Comment by amusi** [comment]
> PSGAN: Pose and Expression Robust Spatial-Aware GAN for Customizable Makeup Transfer
> (CVPR 2020 **Oral**)
> 
> paper: https://arxiv.org/abs/1909.06956
> code: https://github.com/wtjiang98/PSGAN

感谢分享，现已添加！
