### ISSUE TITLE
Point Cloud Segmentation

### ISSUE THREAD

**Issue by yanx27** [amusi/CVPR2020-Code#24]
Hi @amusi, could you update this paper (CVPR2020)

 "PointASNL: Robust Point Clouds Processing using Nonlocal Neural Networks with Adaptive Sampling"

paper:  https://arxiv.org/pdf/2003.00492.pdf
code: https://github.com/yanx27/PointASNL

**Comment by amusi** [comment]
> Hi @amusi, could you update this paper (CVPR2020)
> 
> "PointASNL: Robust Point Clouds Processing using Nonlocal Neural Networks with Adaptive Sampling"
> 
> paper: https://arxiv.org/pdf/2003.00492.pdf
> code: https://github.com/yanx27/PointASNL

感谢分享，现已添加
