### ISSUE TITLE
添加一篇HOI的paper

### ISSUE THREAD

**Issue by YueLiao** [amusi/CVPR2020-Code#25]
PPDM: Parallel Point Detection and Matching for Real-time Human-Object Interaction Detection
https://arxiv.org/pdf/1912.12898
https://github.com/YueLiao/PPDM

**Comment by amusi** [comment]
> PPDM: Parallel Point Detection and Matching for Real-time Human-Object Interaction Detection
> https://arxiv.org/pdf/1912.12898
> https://github.com/YueLiao/PPDM

感谢分享，现已添加
