### ISSUE TITLE
添加一篇GAN用于representation learning的文章 "Distribution-induced Bidirectional Generative Adversarial Network for Graph Representation Learning"

### ISSUE THREAD

**Issue by SsGood** [amusi/CVPR2020-Code#27]
Full-text link: https://arxiv.org/abs/1912.01899
code link: https://github.com/SsGood/DBGAN

**Comment by amusi** [comment]
> Full-text link: https://arxiv.org/abs/1912.01899
> code link: https://github.com/SsGood/DBGAN

感谢分享，现已添加
