### ISSUE TITLE
添加一篇行为轨迹预测的paper

### ISSUE THREAD

**Issue by JunweiLiang** [amusi/CVPR2020-Code#31]
The Garden of Forking Paths: Towards Multi-Future Trajectory Prediction

论文: https://arxiv.org/abs/1912.06445
代码: https://github.com/JunweiLiang/Multiverse
数据集: https://next.cs.cmu.edu/multiverse/

谢谢！

**Comment by amusi** [comment]
感谢分享，现已添加
