### ISSUE TITLE
添加一篇场景文字检测文章

### ISSUE THREAD

**Issue by wangyuxin87** [amusi/CVPR2020-Code#36]
ContourNet: Taking a Further Step Toward Accurate Arbitrary-Shaped Scene Text Detection
论文地址：http://openaccess.thecvf.com/content_CVPR_2020/papers/Wang_ContourNet_Taking_a_Further_Step_Toward_Accurate_Arbitrary-Shaped_Scene_Text_CVPR_2020_paper.pdf
代码地址：https://github.com/wangyuxin87/ContourNet

**Comment by amusi** [comment]
感谢分享，现已添加！
