### ISSUE TITLE
添加一篇3D目标检测论文

### ISSUE THREAD

**Issue by skyhehe123** [amusi/CVPR2020-Code#39]
Structure Aware Single-stage 3D Object Detection from Point Cloud

论文地址：http://openaccess.thecvf.com/content_CVPR_2020/html/He_Structure_Aware_Single-Stage_3D_Object_Detection_From_Point_Cloud_CVPR_2020_paper.html

代码地址：https://github.com/skyhehe123/SA-SSD

谢谢

**Comment by amusi** [comment]
感谢分享，现已添加！
