### ISSUE TITLE
Request for adding a new paper

### ISSUE THREAD

**Issue by SugarRuy** [amusi/CVPR2020-Code#40]
Paper Title: Evade Deep Image Retrieval by Stashing Private Images in the Hash Space

Paper Address: http://openaccess.thecvf.com/content_CVPR_2020/html/Xiao_Evade_Deep_Image_Retrieval_by_Stashing_Private_Images_in_the_CVPR_2020_paper.html

Code Address:  https://github.com/sugarruy/hashstash

Thanks!

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing
