### ISSUE TITLE
Reqest for adding a new paper

### ISSUE THREAD

**Issue by BoyuanChen** [amusi/CVPR2020-Code#42]
Title: Oops! Predicting Unintentional Action in Video
Paper: [https://arxiv.org/abs/1911.11206](https://arxiv.org/abs/1911.11206)
Code: [https://github.com/cvlab-columbia/oops](https://github.com/cvlab-columbia/oops)
Dataset: [https://oops.cs.columbia.edu/data/](https://oops.cs.columbia.edu/data/)
Website: [https://oops.cs.columbia.edu/](https://oops.cs.columbia.edu/)

Thank you!

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing

**Comment by BoyuanChen** [comment]
Thanks a lot!!
