### ISSUE TITLE
Request for adding a new paper

### ISSUE THREAD

**Issue by Blueprintf** [amusi/CVPR2020-Code#43]
Title: An Efficient PointLSTM for Point Clouds Based Gesture Recognition
Paper: http://openaccess.thecvf.com/content_CVPR_2020/html/Min_An_Efficient_PointLSTM_for_Point_Clouds_Based_Gesture_Recognition_CVPR_2020_paper.html
Code: https://github.com/Blueprintf/pointlstm-gesture-recognition-pytorch

Thank you!

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing
