### ISSUE TITLE
添加几篇文章

### ISSUE THREAD

**Issue by zycliao** [amusi/CVPR2020-Code#44]
1. TailorNet: Predicting Clothing in 3D as a Function of Human Pose, Shape and Garment Style
数据集，三维重建
paper:
http://openaccess.thecvf.com/content_CVPR_2020/papers/Patel_TailorNet_Predicting_Clothing_in_3D_as_a_Function_of_Human_CVPR_2020_paper.pdf
code：
https://github.com/chaitanya100100/TailorNet
数据集：
https://github.com/zycliao/TailorNet_dataset

2. Implicit Functions in Feature Space for 3D Shape Reconstruction and Completion
三维重建
paper:
http://openaccess.thecvf.com/content_CVPR_2020/papers/Chibane_Implicit_Functions_in_Feature_Space_for_3D_Shape_Reconstruction_and_CVPR_2020_paper.pdf
code:
https://github.com/jchibane/if-net

3. Learning to Transfer Texture from Clothing Images to 3D Humans
三维重建
paper:
http://openaccess.thecvf.com/content_CVPR_2020/papers/Mir_Learning_to_Transfer_Texture_From_Clothing_Images_to_3D_Humans_CVPR_2020_paper.pdf
code:
https://github.com/aymenmir1/pix2surf

**Comment by amusi** [comment]
感谢分享，现已添加！
