### ISSUE TITLE
please kindly add HOReID

### ISSUE THREAD

**Issue by wangguanan** [amusi/CVPR2020-Code#45]
Thanks for your awesome work.
please kindly add the following Re-ID work.

Title: High-Order Information Matters: Learning Relation and Topology for Occluded Person Re-Identification
Paper: http://openaccess.thecvf.com/content_CVPR_2020/html/Wang_High-Order_Information_Matters_Learning_Relation_and_Topology_for_Occluded_Person_CVPR_2020_paper.html
Code: https://github.com/wangguanan/HOReID

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing
