### ISSUE TITLE
Request for adding a new oral paper

### ISSUE THREAD

**Issue by zxhuang1698** [amusi/CVPR2020-Code#46]
Interpretable and Accurate Fine-grained Recognition via Region Grouping (CVPR 2020, Oral)

Paper: https://arxiv.org/pdf/2005.10411.pdf
Code: https://github.com/zxhuang1698/interpretability-by-parts
Category: 可解释性/图像分类/其他

Thanks!

**Comment by amusi** [comment]
感谢分享，现已添加！
