### ISSUE TITLE
添加一篇GAN论文

### ISSUE THREAD

**Issue by alpc91** [amusi/CVPR2020-Code#48]
Reusing Discriminators for Encoding: Towards Unsupervised Image-to-Image Translation（NICE-GAN）
论文地址：http://openaccess.thecvf.com/content_CVPR_2020/html/Chen_Reusing_Discriminators_for_Encoding_Towards_Unsupervised_Image-to-Image_Translation_CVPR_2020_paper.html
代码地址：https://github.com/alpc91/NICE-GAN-pytorch

**Comment by amusi** [comment]
感谢分享，现已添加！
